DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Game;

GO

CREATE TABLE User(
    UserID INT IDENTITY(1,1) NOT NULL,
    Email NVARCHAR(256) NOT NULL,
    -- [Password] BINARY(64 NOT NULL)
    Password NVARCHAR(64) NOT NULL,
    Role NVARCHAR NOT NULL,
    Authorized BIT,
    CONSTRAINT PK_User PRIMARY KEY (UserID),
    CONSTRAINT UQ_User UNIQUE (Email)
)

CREATE TABLE Game(
    GameID INT IDENTITY(1,1) NOT NULL,
    GameDate DATETIME NOT NULL,
    Venue NVARCHAR(64) NOT NULL,
    UserID INT NOT NULL,
    CONSTRAINT PK_Game Primary KEY (GameID),
    CONSTRAINT FK_Game_Patient FOREIGN KEY (UserID) REFERENCES User
)
